### ISSUE TITLE
Turn plan into issues

### ISSUE THREAD

**Issue by yungyuc** [ExplorerRay/onnxinfo#3]
Could you please create issues to track the work items you planned in [the schedule](https://github.com/yungyuc/nsdhw_24au/blob/ed6f48bf0412b8a5f9324cd055c49a4906700e8c/project/ExplorerRay/README.md?plain=1#L77)?

**Comment by yungyuc** [comment]
The checkins/PRs do not seem to catch up the plan in the schedule.  Do you need any help?

**Comment by ExplorerRay** [comment]
I spent too much time than I thought on dealing with building dependency (Protobuf) environment. And I finally finished this. Although this works right now, it compile for several minutes at first. I think it may cost longer when doing CI in Github Action because of limited resources. Do you have any recommendations?

 About catching up the schedule, I will try my best. If still unable to catch up, I may remove document part.

**Comment by yungyuc** [comment]
You may consider to install protobufs from a package manager on GitHub Actions runner, in the same way as [installing compiler](https://github.com/solvcon/modmesh/blob/2974c14dc8a09661230e9e51c8ed30055c49fed4/.github/workflows/devbuild.yml#L41).  Would you think it may work for you?

Regardless, please create an issue to speed up the dependency installation.  If your project requires protobufs, it seems that you have to install it reasonably fast.

If you have filed the initial issues, you can close this issue.  Create more issues as you go.

**Comment by ExplorerRay** [comment]
Thank you for your advice~
